# Generated by Django 5.2.5 on 2025-08-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_user_role_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
