# Generated by Django 5.2.5 on 2025-08-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_manager', True)), fields=('is_manager',), name='only_one_manager'),
        ),
    ]
