# Generated by Django 5.2.5 on 2025-08-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_total_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
